version: '3'
services:

  server:
    container_name: server
    image: server:latest
    environment:
      - SERVER_PORT=12350
      - LOG_LEVEL=info
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=seba1234
      - N_CONSUMERS=2
    entrypoint: /tp2/target/release/server
    networks:
      - tp2_net

  client:
    container_name: client
    image: client:latest
    environment:
      - SERVER_PORT=12350
      - FILENAME_POSTS=posts_full.csv
      - FILENAME_COMMENTS=comments_full.csv
      - LOG_LEVEL=info
    entrypoint: /tp2/target/release/client
    volumes:
      - ./downloads:/tp2/downloads
      - ./posts.csv:/tp2/posts.csv
      - ./posts_full.csv:/tp2/posts_full.csv
      - ./comments.csv:/tp2/comments.csv
      - ./comments_full.csv:/tp2/comments_full.csv
    depends_on:
      - server
    networks:
      - tp2_net

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=seba1234
    depends_on:
      - server
    networks:
      - tp2_net
    ports:
     - 15672:15672

  worker_initial_state:
    image: worker_initial_state:latest
    deploy:
      mode: replicated
      replicas: 2
    entrypoint: /tp2/target/release/worker_initial_state
    environment:
      - LOG_LEVEL=info
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=seba1234
      - N_PRODUCERS=1 # server
      - N_CONSUMERS=6 # worker_map
    depends_on:
      - server
    networks:
      - tp2_net

  worker_avg:
    container_name: worker_avg
    image: worker_avg:latest
    entrypoint: /tp2/target/release/worker_avg
    environment:
      - LOG_LEVEL=info
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=seba1234
    depends_on:
      - server  
    networks:
      - tp2_net
  
  worker_map:
    image: worker_map:latest
    entrypoint: /tp2/target/release/worker_map
    deploy:
      mode: replicated
      replicas: 6
    environment:
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=seba1234
      - LOG_LEVEL=info
      - N_PRODUCERS=2 # worker_initial_state
    depends_on:
      - server
    networks:
      - tp2_net

  worker_filter_students:
    image: worker_filter_students:latest
    entrypoint: /tp2/target/release/worker_filter_students
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=seba1234
      - LOG_LEVEL=info
    depends_on:
      - server
    networks:
      - tp2_net
  
  worker_filter_score:
    container_name: worker_filter_score
    image: worker_filter_score:latest
    entrypoint: /tp2/target/release/worker_filter_score
    environment:
      - LOG_LEVEL=info
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=seba1234
    depends_on:
      - server
    networks:
      - tp2_net

  worker_join:
    container_name: worker_join
    image: worker_join:latest
    entrypoint: /tp2/target/release/worker_join
    environment:
      - LOG_LEVEL=info
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=seba1234
    depends_on:
      - server
    networks:
      - tp2_net

  worker_group_by:
    container_name: worker_group_by
    image: worker_group_by:latest
    entrypoint: /tp2/target/release/worker_group_by
    environment:
      - LOG_LEVEL=info
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=seba1234
    depends_on:
      - server
    networks:
      - tp2_net

networks:
  tp2_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
