version: '3'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: /target/release/server
    environment:
      - SERVER_PORT=12345
    networks:
      - testing_net

  client:
    container_name: client
    image: client:latest
    entrypoint: /target/release/client
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24